### ISSUE TITLE
Reservation date error: 1 day mismatch

### ISSUE THREAD

**Issue by enric1994** [thomasrepnik/tennis-reservation#9]
Hey Thomas,
First of all, thank you very much for sharing this project. I am using it to setup a booking system for the tennis court in our village.

When I book one day, the reservation is shown on the previous day.
My workaround is changing `Reservation.java`
```
    public void setDatum(LocalDate datum) {
        this.datum = datum.plusDays(1);
    }
```
It solves the problem but if I edit a booking then it jumps to the next day :(

Do you know how to solve this error?

**Comment by enric1994** [comment]
I found out the problem is the time zone because I only get this errors from 8pm onwards. Any idea of how to compensate this?

**Comment by thomasrepnik** [comment]
Glad to see you using this project for making your own tennis reservation system.
i think your problem is, that the date gets converted to utc when it's sent to the backend.
Be aware that this was only a small sample project (and therefore won't get maintained), so there could be more bugs. 

**Example:**
_My timezone is UTC+2. The following code is returning 2020-07-03 23:33:00, because the timezone is applied as soon as it is converted to utc_

```
var now = new Date('2020-07-04 01:33:00').toUTCString()
alert (now)
```

_On your side it's exactly the same, but your UTC Timezone seems to be UTC-4. So everytime your date is converted to UTC 4 hours will be added, and therefore your date is broken after 8pm_

You can use `moment.js`(which is already included in the project to convert the dates as you need it:

**UTC to Local:**
```
var testDateUtc = moment.utc("2020-07-03 23:33:00");
var localDate = moment(testDateUtc).local();
alert(localDate) //shows 2020-07-04 01:33:00 at my timezone
```

**Local to UTC:**
```
var localDate = moment('2020-07-04 01:33:00');
var utcDate = localDate.utc();
alert(utcDate) //shows 2020-07-03 23:33:00 at my timezone
```

Hope this helps a bit.

**Comment by enric1994** [comment]
Thanks for your help! Good to know that the default time zone is UTC
